name: baseflow_plugin_template
description: A template for plugin examples
version: 2.0.0-nullsafety
author:
homepage:

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.0-nullsafety.1

dev_dependencies:
  flutter_test:
    sdk: flutter

#flutter:
#  assets:
#    - lib/assets/logo.png
